### ISSUE TITLE
Add option to generate inheritance diagram of a specific class

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#10]
Add diagram configuration option to generate only inheritance relationships starting from a root (most abstract) class.

**Comment by bkryza** [comment]
This is actually a more generic issue and should be handled by refactoring the filtering mechanism into a more extensible set of inclusive and exclusive rules, e.g. to create an inheritance diagram of ClassA:

```yaml
some_class_diagram:
  # ...
  include:
    subclasses:
      - ns1::ns2::ClassA
    relationships:
      - inheritance
```
or to create a context diagram for ClassB (only direct relatonships from ClassB to other entities)
```yaml
some_class_diagram:
  # ...
  include:
    context:
      - ns1::ns2::ClassA
```

or to show dependencies of ClassC:
```yaml
some_class_diagram:
  # ...
  include:
    dependencies:
      - ns1::ns2::ClassC
```
