### ISSUE TITLE
Cannot Generate UML for Header Only Classes/Projects

### ISSUE THREAD

**Issue by DeveloperPaul123** [bkryza/clang-uml#111]
Not sure if I'm doing something wrong, but while trying to generate UML diagrams on my header only [thread-pool library](https://github.com/DeveloperPaul123/thread-pool), I get the following output:

```
[info] [tid 72992] [C:\clang-uml-tmp\clang-uml\src\main.cc:261] Loaded clang-uml config from .clang-uml
[info] [tid 72992] [C:\clang-uml-tmp\clang-uml\src\main.cc:277] Loading compilation database from D:\Repositories\thread-pool\out\build\x64-debug-clang directory
[error] [tid 72992] [C:\clang-uml-tmp\clang-uml\src\main.cc:422] Diagram classes generation failed: no translation units found
```

**Comment by DeveloperPaul123** [comment]
You can see my setup here: https://github.com/DeveloperPaul123/thread-pool/tree/feature/clang-uml

**Comment by DeveloperPaul123** [comment]
Ok that makes sense. 

But to be clear, do you mean the glob entry in the `.clang-uml` file or the `file(GLOB_RECURSE...)` in my library's CMakeLists.txt?

**Comment by bkryza** [comment]
@DeveloperPaul123 Sorry, I meant `.clang-uml` file. I've just tried your branch on Ubuntu with the following config:

```yaml
# Directory containing the compile_commands.json file
compilation_database_dir: out/build/x64-debug-clang
# The directory where *.puml files will be generated
output_directory: documentation/diagrams
# Set this as default for all diagrams
generate_method_arguments: none
debug_mode: on
# Enable generation of hyperlinks to diagram elements
generate_links:
  # Link pattern
  link: "https://github.com/DeveloperPaul123/thread-pool/blob/{{ git.commit }}/{{ element.source.path }}#L{{ element.source.line }}"
  # Tooltip pattern
  tooltip: "{{ element.name }}"
# The map of diagrams - keys are also diagram file names
diagrams:
  classes:
    type: class
    # Limiting the number of files to include can significantly
    # improve the generation time
    glob:
      - test/source/thread_pool.cpp
      - test/source/thread_safe_queue.cpp
    include:
      # Only include entities from the following namespaces
      namespaces:
        - dp
    # Specify customized relationship hints for types which are
    # arguments in template instantiations
    relationship_hints:
      # All tuple arguments should be treated as aggregation
      std::tuple: aggregation
    plantuml:
      # Add this line to the beginning of the resulting puml file
      before:
        - 'title thread-pool class diagram model'
```

However I had to put this line at the very top of `thread_pool.cpp` and `thread_safe_queue.cpp`, as `doctest` uses some deprecated variable length arrays, which clang does not accept any more and fails:
```cpp
#pragma clang diagnostic ignored "-Wvla-extension"
```

After that I got the diagram:
```plantuml
@startuml
title thread-pool class diagram model
' /home/bartek/devel/clang-uml-issues/111/thread-pool/include/thread_pool/thread_safe_queue.h:24
class "dp::thread_safe_queue<T,Lock>" as C_0000405729281244953959
class C_0000405729281244953959 [[https://github.com/DeveloperPaul123/thread-pool/blob/695d0efd0f4a89342bbc5f389e9ee194ba8c150a/include/thread_pool/thread_safe_queue.h#L24{thread_safe_queue}]] {
' :0
+thread_safe_queue<T, Lock>() = default : void
' :0
+push() : void
' :0
+empty() const : bool
' :0
+pop() : std::optional<T>
' :0
+steal() : std::optional<T>
' /home/bartek/devel/clang-uml-issues/111/thread-pool/include/thread_pool/thread_safe_queue.h:60
-data_ : std::deque<T> [[[https://github.com/DeveloperPaul123/thread-pool/blob/695d0efd0f4a89342bbc5f389e9ee194ba8c150a/include/thread_pool/thread_safe_queue.h#L60{data_}]]]
' /home/bartek/devel/clang-uml-issues/111/thread-pool/include/thread_pool/thread_safe_queue.h:61
-mutex_ : Lock [[[https://github.com/DeveloperPaul123/thread-pool/blob/695d0efd0f4a89342bbc5f389e9ee194ba8c150a/include/thread_pool/thread_safe_queue.h#L61{mutex_}]]]
}
' /home/bartek/devel/clang-uml-issues/111/thread-pool/include/thread_pool/thread_pool.h:35
class "dp::thread_pool<FunctionType,ThreadType>" as C_0001252936495970643718
class C_0001252936495970643718 [[https://github.com/DeveloperPaul123/thread-pool/blob/695d0efd0f4a89342bbc5f389e9ee194ba8c150a/include/thread_pool/thread_pool.h#L35{thread_pool}]] {
' :0
+thread_pool<FunctionType, ThreadType>() : void
' :0
+~thread_pool<FunctionType, ThreadType>() : void
' :0
+thread_pool<FunctionType, ThreadType>() : void
' :0
+operator=() : thread_pool<FunctionType,ThreadType> &
' :0
+size() const : auto
' :0
+enqueue() : std::future<ReturnType>
' :0
+enqueue_detach() : void
' :0
-enqueue_task() : void
' /home/bartek/devel/clang-uml-issues/111/thread-pool/include/thread_pool/thread_pool.h:194
-threads_ : std::vector<ThreadType> [[[https://github.com/DeveloperPaul123/thread-pool/blob/695d0efd0f4a89342bbc5f389e9ee194ba8c150a/include/thread_pool/thread_pool.h#L194{threads_}]]]
' /home/bartek/devel/clang-uml-issues/111/thread-pool/include/thread_pool/thread_pool.h:195
-tasks_ : std::deque<task_item> [[[https://github.com/DeveloperPaul123/thread-pool/blob/695d0efd0f4a89342bbc5f389e9ee194ba8c150a/include/thread_pool/thread_pool.h#L195{tasks_}]]]
' /home/bartek/devel/clang-uml-issues/111/thread-pool/include/thread_pool/thread_pool.h:196
-count_ : std::size_t [[[https://github.com/DeveloperPaul123/thread-pool/blob/695d0efd0f4a89342bbc5f389e9ee194ba8c150a/include/thread_pool/thread_pool.h#L196{count_}]]]
' /home/bartek/devel/clang-uml-issues/111/thread-pool/include/thread_pool/thread_pool.h:197
-pending_tasks_ : std::atomic_int_fast64_t [[[https://github.com/DeveloperPaul123/thread-pool/blob/695d0efd0f4a89342bbc5f389e9ee194ba8c150a/include/thread_pool/thread_pool.h#L197{pending_tasks_}]]]
}
' :0
class "dp::thread_safe_queue<FunctionType>" as C_0000103771545600101984
class C_0000103771545600101984 {
}
' /home/bartek/devel/clang-uml-issues/111/thread-pool/include/thread_pool/thread_pool.h:189
class "dp::thread_pool::task_item" as C_0001317959859440874329
class C_0001317959859440874329 [[https://github.com/DeveloperPaul123/thread-pool/blob/695d0efd0f4a89342bbc5f389e9ee194ba8c150a/include/thread_pool/thread_pool.h#L189{thread_pool##task_item}]] {
' /home/bartek/devel/clang-uml-issues/111/thread-pool/include/thread_pool/thread_pool.h:190
+tasks : dp::thread_safe_queue<FunctionType> [[[https://github.com/DeveloperPaul123/thread-pool/blob/695d0efd0f4a89342bbc5f389e9ee194ba8c150a/include/thread_pool/thread_pool.h#L190{tasks}]]]
' /home/bartek/devel/clang-uml-issues/111/thread-pool/include/thread_pool/thread_pool.h:191
+signal : std::binary_semaphore [[[https://github.com/DeveloperPaul123/thread-pool/blob/695d0efd0f4a89342bbc5f389e9ee194ba8c150a/include/thread_pool/thread_pool.h#L191{signal}]]]
}
C_0000103771545600101984 ..|> C_0000405729281244953959
C_0001317959859440874329 --+ C_0001252936495970643718
C_0001317959859440874329 o-- C_0000103771545600101984 : +tasks
@enduml
```

**Comment by bkryza** [comment]
Yes, you need to specify `glob:` patterns in `.clang-uml` that will match at least on file in your `compile_commands.json`, in other words the `glob:` section tells `clang` which translation units and their includes should be traversed.

The less files these `glob:` patterns match the faster it will work - but make sure that these files include all headers that are necessary to discover all relationships - I now this is inconvenient in practice but I haven't found a more automated way for this.

You can always just skip the `glob:` section but then it will traverse all translation units which will be very slow especially if you have multiple diagrams.

As to the include filters, one option is the namespace filter i.e.:

```yaml
include:
  namespaces: [dp]
```

but there are many others: https://github.com/bkryza/clang-uml/blob/master/docs/diagram_filters.md

Actually I've just noticed there is one undocumented - `paths` - which allows you to limit the diagram to definitions in specific files (not necessarily translation units), e.g.:

```yaml
include:
  paths:
    - include/thread_pool/thread_pool.h
    - include/thread_pool/thread_safe_queue.h
```


You can also browse through the [documentation generated by test cases](https://github.com/bkryza/clang-uml/blob/master/docs/test_cases.md), which contains many examples of things that should work as they are tested on every build :-)
