### ISSUE TITLE
Add option to disable generation of dependency relation to template arguments

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#141]
Currently, the default behavior is that any template argument, which is a class included in the diagram, is linked by a dependency to the template class where it is used.

Sometimes this is not what we want as it can lead to very complex diagrams.

We can either add a global option for this, or add a specialized include filter for template argument dependencies, e.g.:
```yaml
exclude:
  relationships:
    - template_dependencies
```
