### ISSUE TITLE
Add debug log with information which filter rejected some element

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#147]
Currently it is very difficult to figure out why specific element e.g. a class, was not included in the diagram. Usually this is caused by improper filters definition.

There should be a log entry in the verbose log with information on which filter rejected any of the elements (this could be a lot - but it will be limited to translation units specified by `glob` pattern and system headers are skipped by default anyway...)

**Comment by rob-weiss** [comment]
Is there any workaround until this is implemented? When I run

```bash
clang-uml --progress -vvv --remove-compile-flag -Wno-error=class-memaccess --remove-compile-flag -rdynamic --print-from -n example_class_diagram | grep RsbLoc::StationaryLocations::StationaryLocations
```

I get 

```cpp              
Dc::Per::RsbLoc::StationaryLocations::StationaryLocations(const ObstacleSensorRoad::sensor_type &,const ::Per::Frames::Rot1dAcc2dFor &,const TrackedPolylines &)
```
 
When I copy the output to my generated `.uml-clang` file, it generates an almost empty `.puml` file.

```puml
@startuml

'Generated with clang-uml, version 0.4.0
'LLVM version Ubuntu clang version 12.0.0-3ubuntu1~20.04.5
@enduml
```

It works fine for `type: class`. Here's my config:

```yaml
# Change to directory where compile_commands.json is
compilation_database_dir: /workspaces/repos/pj-dc_int/build/unittests/compile_commands.json
# Change to directory where diagram should be written
output_directory: diagrams
diagrams:
  example_class_diagram:
    type: sequence
    glob:
      - src/*.cpp
    using_namespace:
      - Dc::Per::RsbLoc
    include:
      namespaces:
        - Dc::Per::RsbLoc
    exclude:
      namespaces:
        - myproject::detail
    from:
      - function: "Dc::Per::RsbLoc::StationaryLocations::StationaryLocations(const ObstacleSensorRoad::sensor_type &,const ::Per::Frames::Rot1dAcc2dFor &,const TrackedPolylines &)"
```

```bash
clang-uml --version                                                                                                                         ─╯
clang-uml 0.4.0
Copyright (C) 2021-2023 Bartek Kryza <bkryza@gmail.com>
Linux x86_64 3.10.0-1160.95.1.el7.x86_64
Built against LLVM/Clang libraries version: 12.0.0
Using LLVM/Clang libraries version: Ubuntu clang version 12.0.0-3ubuntu1~20.04.5
```
