### ISSUE TITLE
Add `from_to` option to sequence diagram

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#154]
Currently, sequence diagrams support only one constraint - `start_from` which is open ended, i.e. it will generate a sequence diagram with all call sequences originating from a given function or method.

Sometimes, it is nice to know what call sequence leads from one function or method to another, this could be achieved by adding `from_to` option, e.g.

```yaml
    from_to:
      - [function: "main(int,const char**)",
         function: "ns1::ClassA::add(int,int)"]
```
