### ISSUE TITLE
Relationships to classes in smart pointers not as documented

### ISSUE THREAD

**Issue by cdelledonne** [bkryza/clang-uml#182]
Hi, thanks for this great piece of free software!

## Expected behavior

The section of the documentation [Relationships to classes in containers or smart pointers](https://clang-uml.github.io/md_docs_2class__diagrams.html#relationships-to-classes-in-containers-or-smart-pointers) claims that class members that are wrapped in smart pointers will have a relationship with the class wrapped by the smart pointers.

E.g. a piece of code like this:

```cpp
class A { };
 
class B { };
 
class C { };
 
class R {
public:
    std::unique_ptr<A> a;
    std::shared_ptr<B> b;
    std::weak_ptr<C> c;
};
```

should results in the following diagram:

![image](https://github.com/bkryza/clang-uml/assets/24732205/da013d0e-500e-4b22-8dec-f00f9689c5cb)

## Observed behavior

What I actually get on my end is a diagram where the smart pointer classes are explicit in the diagram:

![class_diagram](https://github.com/bkryza/clang-uml/assets/24732205/876a2b00-5f59-49eb-97ea-0bb1482e99d0)

Am I doing something wrong?

## To reproduce

I invoke `clang-uml` and `plantuml` as follows:

```
clang-uml
plantuml -tpng diagrams/class_diagram.puml
```

This is my `clang-uml` config:

```yaml
compilation_database_dir: .
output_directory: diagrams
diagrams:
  class_diagram:
    type: class
```

This is the version of `clang-uml` I'm using:

```
clang-uml 0.4.0
Copyright (C) 2021-2023 Bartek Kryza <bkryza@gmail.com>
Linux x86_64 6.5.5-200.fc38.x86_64
Built against LLVM/Clang libraries version: 16.0.6
Using LLVM/Clang libraries version: clang version 16.0.6 (Fedora 16.0.6-3.fc38)
```

And this is the output of `clang-uml`:

```puml
@startuml
class "std::unique_ptr<A>" as C_0001975126611825318673
class C_0001975126611825318673 {
__
}
class "std::shared_ptr<B>" as C_0002209144055526958115
class C_0002209144055526958115 {
__
}
class "std::weak_ptr<C>" as C_0001668153567094565337
class C_0001668153567094565337 {
__
}
class "A" as C_0000864916647665253425
class C_0000864916647665253425 {
__
}
class "B" as C_0000524968816257364797
class C_0000524968816257364797 {
__
}
class "C" as C_0001554042629321205376
class C_0001554042629321205376 {
__
}
class "R" as C_0001278814269199330324
class C_0001278814269199330324 {
__
+a : std::unique_ptr<A>
+b : std::shared_ptr<B>
+c : std::weak_ptr<C>
}
C_0001975126611825318673 ..> C_0000864916647665253425
C_0002209144055526958115 ..> C_0000524968816257364797
C_0001668153567094565337 ..> C_0001554042629321205376
C_0001278814269199330324 o-- C_0001975126611825318673 : +a
C_0001278814269199330324 --> C_0000524968816257364797 : +b
C_0001278814269199330324 --> C_0002209144055526958115 : +b
C_0001278814269199330324 --> C_0001554042629321205376 : +c
C_0001278814269199330324 --> C_0001668153567094565337 : +c

'Generated with clang-uml, version 0.4.0
'LLVM version clang version 16.0.6 (Fedora 16.0.6-3.fc38)
@enduml
```

**Comment by bkryza** [comment]
@cdelledonne It actually works as expected, you have not excluded `std` namespace in your config, so either try:

```yaml
compilation_database_dir: .
output_directory: diagrams
diagrams:
  class_diagram:
    type: class
  exclude:
    namespaces:
      - std
```

or if your code is inside some namespace already (e.g. `myns`), try:

```yaml
compilation_database_dir: .
output_directory: diagrams
diagrams:
  class_diagram:
    type: class
  include:
    namespaces:
      - myns
```
