### ISSUE TITLE
Paths filter does not work on Linux for class diagrams

### ISSUE THREAD

**Issue by njamb94** [bkryza/clang-uml#189]
For class diagrams, when using paths within include/exclude filters, files (classes from files) are not filtered.

The issue is present when using absolute and relative paths, including full paths (with file name) and globs.

What I have gathered from debugging the code, the problem for class diagrams is that all paths received within the common::model::source_file constructor are relative (regardless of their definition within .clang-uml) and is_relative flag is always set to true.

When match filter for common::model::source_file is called from diagram_filter.cc (from common::model namespace), the path is always relative and the function returns an empty object for tvl::value_t. By doing so, the path is never matched and so the file is not filtered.

When adding std::filesystem::absolute(preferred) within the constructor, and overwriting preferred path's value with absolute path, the problem is resolved.

The problem is also present when generating diagram for the test case t00061.

Not sure if the problem is present for other diagram types. Only tested for class diagrams on releases v0.3.9 and v0.4.0.

**Comment by bkryza** [comment]
@njamb94 Can you share your config file? Also can you try to set `relative_to` option to an approriate path, in the simplest case it can be:
```yaml
    relative_to: .
```

`The problem is also present when generating diagram for the test case t00061.` - I don't understand this statement - The test case passes and it filters out all classes not declared in `include/*_a.h`

**Comment by njamb94** [comment]
Of course, here is the config file of the _t00061_:
```
compilation_database_dir: .
output_directory: diagrams
remove_compile_flags:
  - '-fno-canonical-system-headers'
diagrams:
  t00061_class:
    type: class
    relative_to: .
    glob:
      - t00061.cc
    include:
      namespaces:
        - clanguml::t00061
      paths:
        - include/*_a.h
    using_namespace:
      - clanguml::t00061
```
I have created a bazel workspace within _tests/t00061_ directory. The same directory contains _compile_commands.json_ file.

I have set
```
relative_to: .
```
to be the root directory of _t00061_ as it functions as root directory for this "mini-project".

Clang-uml is executed from within _t00061_ directory as well.

With this configuration, I expected the output to be only class A, but instead I get all three classes (A, B and C).

I have managed to "fix" the issue by adding
```
preferred = std::filepath::absolute(preferred);
```
in the _common::model::source_file_'s constructor after assignment:
```
auto preferred = &p;
```

Hope this info helps.
