### ISSUE TITLE
Incomplete sequence diagram generated

### ISSUE THREAD

**Issue by cimplart** [bkryza/clang-uml#224]
Using clang-uml 0.4.2 (installed from Ubuntu PPA)

.clang-uml file:

```
compilation_database_dir: .
output_directory: docs/diagrams
add_compile_flags: 
  - -std=c++17
diagrams:
  node_graph_notify_graph_change_sequence:
    type: sequence
    generate_condition_statements: true
    glob:
      - src/rclcpp/node_interfaces/node_graph.cpp
    using_namespace:
      - rclcpp
    include:
      namespaces:
        - rclcpp
    exclude:
      namespaces:
        - std
    from: 
      - function: "rclcpp::node_interfaces::NodeGraph::notify_graph_change()"
```  

C++ code of the function:

```
void NodeGraph::notify_graph_change()
{
  {
    std::lock_guard<std::mutex> graph_changed_lock(graph_mutex_);
    bool bad_ptr_encountered = false;
    for (auto & event_wptr : graph_events_) {
      auto event_ptr = event_wptr.lock();
      if (event_ptr) {
        event_ptr->set();
      } else {
        // -->
        bad_ptr_encountered = true;
       // <--
      }
    }
    // -->
    if (bad_ptr_encountered) {
      // remove invalid pointers with the erase-remove idiom
      graph_events_.erase(
        std::remove_if(
          graph_events_.begin(),
          graph_events_.end(),
          [](const rclcpp::Event::WeakPtr & wptr) {
            return wptr.expired();
          }),
        graph_events_.end());
      // update graph_users_count_
      graph_users_count_.store(graph_events_.size());
    }
  }
  graph_cv_.notify_all();
  // <--
  auto & node_gc = node_base_->get_notify_guard_condition();
  try {
    node_gc.trigger();
  } catch (const rclcpp::exceptions::RCLError & ex) {
    throw std::runtime_error(
            std::string("failed to notify wait set on graph change: ") + ex.what());
  }
}
```

Generated sequence:

```
@startuml
participant "node_interfaces::NodeGraph" as C_0000297654742416732392
[-> C_0000297654742416732392 : notify_graph_change()
activate C_0000297654742416732392
loop graph_events_
alt event_ptr
participant "Event" as C_0001049320115598860856
C_0000297654742416732392 -> C_0001049320115598860856 : set()
activate C_0001049320115598860856
C_0001049320115598860856 --> C_0000297654742416732392
deactivate C_0001049320115598860856
else
end
end
participant "node_interfaces::NodeBaseInterface" as C_0001584589276004128081
C_0000297654742416732392 -> C_0001584589276004128081 : get_notify_guard_condition()
activate C_0001584589276004128081
C_0001584589276004128081 --> C_0000297654742416732392
deactivate C_0001584589276004128081
group try
participant "GuardCondition" as C_0000331558648505401301
C_0000297654742416732392 -> C_0000331558648505401301 : trigger()
activate C_0000331558648505401301
deactivate C_0000331558648505401301
else const rclcpp::exceptions::RCLError &
end
deactivate C_0000297654742416732392

'Generated with clang-uml, version 0.4.2
'LLVM version Ubuntu clang version 15.0.7
@enduml
```

Issue: the parts of the source code (marked with // <-- and // --> comments) are not shown on the sequence diagram at all. The diagram is incomplete.
The source code is from the ROS2 Humble. Build instructions are found on [this page](https://docs.ros.org/en/humble/Installation/Alternatives/Ubuntu-Development-Setup.html)
