### ISSUE TITLE
Add support to remove compile flags in config files based on regex

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#303]
Currently, the option `remove_compile_flags` only accepts string values, which means that all flags which need to be removed must be provided explicitly, e.g:

```yaml
remove_compile_flags:
  - -mpreferred-stack-boundary=3
  - -mindirect-branch=thunk-extern
  - -mindirect-branch-register
  - -fconserve-stack
  - -falign-jumps=1
  - -mrecord-mcount
  - -fsanitize=bounds-strict
```

It would be nice to allow regex so that for instance it would be possible to define them as:

```yaml
remove_compile_flags:
  - r: '-m.*'
  - -fno-allow-store-data-races
  - -fconserve-stack
  - -falign-jumps=1
  - r: '-fsanitize=.*'
```
