### ISSUE TITLE
Exclude specific methods

### ISSUE THREAD

**Issue by huwpascoe** [bkryza/clang-uml#326]
I'm trying to create a diagram to help visualize Godot classes. The Object model has a huge number of generated methods (some static, some override from Object) that are present in every class, but shouldn't be part of the diagram.

```puml
{static} #_bind_methods() : void
{static} #_get_bind_compatibility_methods() : void (*)()
{static} #_get_bind_methods() : void (*)()
+_get_class_namev() const : const StringName *
#_get_get() const : bool (Object::*)(const StringName &,Variant &) const
...
```

The documentation seems to imply the use of "element" to specify methods to exclude, which I've tried:

```yaml
diagrams:

    #...

    exclude:
      elements:
        - _get_get                    # nope
        - _get_get()                  # nope
        - TheClassName::_get_get      # nope
        - r: '.*_get_get.*'           # nope
        - r: '_get_get'               # nope
        - '#_get_get'                 # nope
        - '_get_get() const : bool (Object::*)(const StringName &,Variant &) const' # nope
```

But I can't get anything to work.

Am I doing it wrong or is filtering methods not supported?

**Comment by bkryza** [comment]
@huwpascoe Currently, filtering class methods or members by name is not possible, although it's a good point that it should be possible and it shouldn't be too difficult to implement. What you currently can do, is limit methods by:

- access scope, e.g.
  ```yaml
  exclude:
    access:
      - protected
      - private
  ```

- method type, e.g.:
  ```yaml
  exclude:
    method_types:
      - constructor
      - destructor
      - operator
      - assignment
      - static
  ```

I'll look into adding the method and member filtering based on name or regex...

**Comment by bkryza** [comment]
@huwpascoe I've added support for extended `elements` filter definition, which allows to specify a type of the element to which the pattern is applied, and also allows matching methods and member variables in classes.

If you can build the latest `master` branch from sources, the following filter definition should work for you (you may need to adjust the regex a little):
```yaml
    exclude:
      elements:
        - type: method
          name:
            r: '.*::_get_get'
```
