### ISSUE TITLE
Extend element diagram filter with element types

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#328]
Currently the element diagram filter only allows filtering based on name or regex, however it is not possible to specify that the name pattern should only apply to specific element types such as classes, methods etc, for example the following should be possible:

```yaml
    include:
      elements:
        - type: class
          name: 'MyType.+'
    exclude:
      elements:
        - type: method
          name:
            r: '.+get.+'
```

It should also extend for methods whose filtering by name is currently not possible (#326).

**Comment by lipi** [comment]
I tried and failed to remove enums from diagrams, using the following config with release 0.5.6:
```
    exclude:
      element_types:
        - enum  # doesn't work
      elements:
        - type: enum
          name:
            r: '.*' # doesn't work either
```
The enums I'm trying to remove are declared like this:
```
typedef enum {
...
} foo_t;
```
