### ISSUE TITLE
Add support for `typedef enum`

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#346]
I tried and failed to remove enums from diagrams, using the following config with release 0.5.6:
```
    exclude:
      element_types:
        - enum  # doesn't work
      elements:
        - type: enum
          name:
            r: '.*' # doesn't work either
```
The enums I'm trying to remove are declared like this:
```
typedef enum {
...
} foo_t;
```

_Originally posted by @lipi in https://github.com/bkryza/clang-uml/issues/328#issuecomment-2502390809_

Currently `clang-uml` does not support `typedef enum` style of enum declaration, since such enum is in fact anonymous and at the moment these are only allowed in class field definitions.

Since this style of enum declaration is commonplace, they should be represented in the diagrams as regular enums.
