### ISSUE TITLE
Enable regular expressions in sequence diagram from, to and from_to conditions

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#366]
Currently, boundary conditions for sequence diagrams have to match exactly the function/method signature which can be tricky. `from`, `to` and `from_to` should also accept regular expressions, e.g.:

```yaml
  from:
    - function:
        r: ".*main.*"
```
