### ISSUE TITLE
Exlcude behaving in unexpecteds ways

### ISSUE THREAD

**Issue by scornsaber** [bkryza/clang-uml#372]
The following is in my clang-uml file, but when generating the diagram I still get issues related to test.cpp. If I remove test.cpp completely the diagram generates with no issues.

exclude:
    paths:
         - src/test.cpp

**Comment by bkryza** [comment]
@scornsaber Thing number one to understand about exclude paths filter, is that it simply tells `clang-uml` to not include any declarations found in `src/test.cpp`, but it will still be processed if `glob` resolves to this file. If you wan't to skip processing of this file, you have to put it in `glob`, e.g:

```yaml
  glob:
    # Include all cpp files directly under src
    include:
      - src/*.cpp
    # Except test.cpp
    exclude:
      - src/test.cpp      
  include:
    # Include in the diagram only declarations found somehere under src directory
    paths:
      - src
```

and then you put

**Comment by scornsaber** [comment]
Thank you for the quick response!

That is what I initially thought but I get a schema error when I put include or exclude within glob.


    glob:
      include:
        - src/*.cpp
        - src/*.h
        - src/*.hpp
      exclude:
        - src/test.cpp
    include:
      paths:
        - src

**Comment by bkryza** [comment]
@scornsaber Ok sorry I forgot it is not in the `0.5.6` release only on `master`. If you can't build the latest master from source, I'm finalizing `0.6.0` it should be out tomorrow...

For now however, you can use a regular expression in the glob instead, something like:
```yaml
glob:
    - r: "src/(?!test.cpp$)[^/]+cpp"
include:
  paths:
    - src
```

You might need to adjust the regex as I didn't test it :-)
