### ISSUE TITLE
How to parse sequence diagram from int main(int argc, char* argv[])

### ISSUE THREAD

**Issue by derived-coder** [bkryza/clang-uml#386]
```
 Failed to find participant matching 'main(int, char*[])' for 'from' condition:
```

In the cpp the function is defined as following:
```
int main(int argc, char* argv[])
```

`.clang-uml`
```
    from:
        - function: main(int, char*[])
```

**Comment by bkryza** [comment]
@derived-coder The function signature must either match exactly how it is visible by Clang or you can use a regex (but you have to make sure it matches just one function in your code).

If you want the exact signature, you can print all function/method signatures that are available for a specific diagram like this:

```
clang-uml --print-from -n my_sequence_diagram | grep main
```

and then copy the printed main function signature to the config exactly.


Or you can just use regex, then change your config `from` section to:

```
   from:
     r: "main.*"
```

**Comment by derived-coder** [comment]
okay, how does clang sees a function like this:
```
int main(int argc, char* argv[])
```
?

**Comment by bkryza** [comment]
@derived-coder Unfortunately that depends on your LLVM version and your platform, that's why you have to run this command:

```
clang-uml --print-from -n my_sequence_diagram | grep main
```

to find out.

**Comment by derived-coder** [comment]
When doing:

> clang-uml --print-from -n my_sequence_diagram | grep main

I got no output, after several seconds of run.

Anyway, my config file is:

```
compilation_database_dir: build
output_directory: puml
add_compile_flags:
  - -fparse-all-comments
  - -fretain-comments-from-system-headers
diagrams:
  my_sequence_diagram:
    title: "My Sequence Diagram"
    type: sequence
    glob:
      - src/some_file.cpp
    include_system_headers: false
    include:
      elements:
        - r: ".*"
    exclude:
      elements:
        - r: "std::forward.*"
    generate_message_comments: true
    from:
        - function:
            r: "main.*"

```

The problem is, I do not see every for every created object a sequence diagram, it stops after some functions calls.
Afterwards I create more objects and invoke some methods, but they are not in the diagram. Not sure what the reason is.
I got following message:
```
] Multiple compile commands detected for file '...../some_file.cpp' in diagram 'my_sequence_diagram' - using only the first one...
```
Could this be an issue?

**Comment by bkryza** [comment]
@derived-coder does `src/some_file.cpp` contain a main function? The `glob` config property tells `clang-uml` which translation units should be processed (a translation is a cpp file and all headers it includes). If you want to process all files in `compile_commands.json` remove `glob` from your config - although this way it can take a while if you have a lot of source files.

The warning `Multiple compile commands detected for file...` is related to the fact that your `compile_commands.json` contains several compile commands for `some_file.cpp`. This is not necessarily a problem, but in general it is not possible to combine call expressions from different compile commands for the same file, so currently `clang-uml` just uses the first one encountered in the `compile_commands.json`. 

If you are missing some calls in your diagrams, it's either a bug in `clang-uml` or you're missing some translation units in your `glob` property. If it's the former, can you describe if this is around some strange template or lambda feature - regular function/method calls are pretty well tested.

As to question 2, just replace your filters: 

```
    include:
      elements:
        - r: ".*"
    exclude:
      elements:
        - r: "std::forward.*"
```

with:

```
    include:
      namespaces:
        - my::namespace
```

The above will include only elements in that namespace and nothing else. There's a documentation for diagram filters mechanism [here](https://clang-uml.github.io/md_docs_2diagram__filters.html#namespaces).

**Comment by derived-coder** [comment]
I use 0.6.0 version.
this is the main.cpp
```

#include <iostream>

namespace foo::bar
{
void some_func()
{
    std::cout << "some func " << std::endl;
}
} // namespace foo::bar

int main(int argc, char* argv[])
{
    foo::bar::some_func();
    return 0;
}
```

.clang-uml config file
```
compilation_database_dir: build
output_directory: puml
diagrams:
  my_sequence_diagram:
    title: "My Sequence Diagram"
    type: sequence
    glob:
      - src/main.cpp
    include_system_headers: false
    include:
      namespaces:
        - foo
    generate_message_comments: true
    from:
        - function:
            r: "main.*"

```

Output:
```src/main.cpp' in diagram 'my_sequence_diagram' - using only the first one...
[error] [tid 2188] [generators.cc:375] Failed to generate diagram 'my_sequence_diagram': Generation of sequence diagram 'my_sequence_diagram' failed due to: Diagram configuration resulted in empty diagram.
ERROR: Failed to generate diagram 'my_sequence_diagram': Generation of sequence diagram 'my_sequence_diagram' failed due to: Diagram configuration resulted in empty diagram.
```

What am I doing wrong?

**Comment by bkryza** [comment]
@derived-coder Ok, so basically the problem at the moment is the namespace filter, which only includes in the diagram elements in namespace `foo` and your `main()` function is not in that namespace so the diagram is empty as the starting point is not in that namespace.

You have 2 options here:
- if what you really want is to just include in the diagram elements from your code base, change namespace filter to `paths` filter and specify that only elements from a specific subdirectory should be included, e.g.:

```yaml
    include:
      paths:
        - src
```

- use advanced filter mode which allows for more complex filtering logic:
```yaml
    filter_mode: advanced
    include:
      # Include only elements allowed by any of the filters below:
      anyof:
        namespaces:
          - foo
        elements:
          - r: "main.*"
```

or

```yaml
    filter_mode: advanced
    include:
      # Include only elements allowed by any of the filters below:
      anyof:
        namespaces:
          - foo
        paths:
          - src/main.cpp
```

**Comment by derived-coder** [comment]
okay, this works better.
However in my real case I still have problems with. It seems to be that classes which are included form some other location, which matches the namespace, are not included into the filter. I do not see anything. What is the solution there?

**Comment by derived-coder** [comment]
I have following scenario. I have a a test case component, my main.cpp, this is using some header only library, which I want to have a sequence diagram from. The header files are laying in a complete different folder, so I use relative paths. For some reason clang-uml is not seeing my third party lib, when I instance a class from it. 

So now I wonder how I set my glob and my path variable in yaml?

**Comment by bkryza** [comment]
@derived-coder The `glob` variable shouldn't need any headers at all as long as they are included directly or indirectly from the source files covered by `glob`.

Can you make the following experiment, assuming your `glob` is correct, i.e. it includes source files which then include your third party library headers, remove the `include:` filter completely and just add:


```yaml
   exclude:
     namespaces:
       - std
```
which should include in diagram everything except `std` namespace, and see if you have your classes and calls in the diagram. If yes, then you can add more filters to limit what you see there.

If you don't then I will need some more information to reproduce the problem (e.g. are these calls made through some lambda passed as argument to std algorithm?).

**Comment by derived-coder** [comment]
The experiment, just shows me one more function from a header file, which is local to the main.cpp.
The rest I see are lambdas and function, which are local, but every other symbol, which is using third party header is not shown. The third party header is in a completely different folder (e.g. I use conan, so completely different location, path come via find_package).
I see the absolute path in the compile_commands.json, however.
The code I instantiate are mostly class templates, using sub namespaces from the root namespace.

**Comment by bkryza** [comment]
@derived-coder Can you share your complete `.clang-uml` config? You can anonymize the file and namespace names, I just need to see the structure...

**Comment by derived-coder** [comment]
```
compilation_database_dir: build
output_directory: puml
diagrams:
  my_sequence_diagram:
    title: "My Sequence Diagram"
    type: sequence
    glob: [ src/main.cpp, include/, include/*.hpp]

    include_system_headers: false
    filter_mode: advanced
    combine_free_functions_into_file_participants: true
    include:
      paths: [ include/, src/ ]

      # Include only elements allowed by any of the filters below:
      anyof:
        namespaces:
          - my_ns
        elements:
          - r: "main.*"
    generate_message_comments: true
    from:
        - function:
            r: "main.*"
```

**Comment by bkryza** [comment]
@derived-coder Ok, try this:

```yaml
compilation_database_dir: build
output_directory: puml
diagrams:
  my_sequence_diagram:
    title: "My Sequence Diagram"
    type: sequence
    glob: [src/main.cpp]
    combine_free_functions_into_file_participants: true
    exclude:
      namespaces:
        - std
    from:
        - function:
            r: "main.*"
```

Now if with this diagram config you don't see the code from the thirdparty library, can you explain how are the methods from the thirdparty library called from your `main()` function? In a sequence diagram when you set the starting point for instance to `main()`, it will only render functions/methods reachable from `main()`. Is the code you want to see even called from `main()`?

**Comment by derived-coder** [comment]
Okay code diagram is printed till this:
```
    using SomeType =
        my_ns::sub_ns::ConreteClass<A, B, 12>;

    
    my_ns::Foo<int> f; // is shown in diagram!!
    SomeType obj(config1, name.c_str(), name2.c_str()); // this ctor call is NOT shown in diagram and all the sub calls in the ctor as well not shown

```

**Comment by bkryza** [comment]
@derived-coder Ok, I will try to reproduce it. In general constructors work e.g. [here](https://clang-uml.github.io/md_docs_2test__cases_2t20030.html), but TBH I don't remember checking for aliased and templated constructors...

**Comment by bkryza** [comment]
@derived-coder I've tried to reproduce but in my case calls from template constructors with using alias work just, so this must something else. Ok, another thing we can try to is go look at verbose logs. Please try to rerun `clang-uml` with `-vv` flag and look for log lines containing:

- `Visiting cxx construct expression`
- `Visiting call expression`

These lines should have an exact source file, line number and column - can you see the call to this constructor and the calls generated in the body of this constructor?

One more thing, is the body of this constructor defined in a header included by main (I assume it should be since it's a template?) or is it just declared in the header file and defined in the library somewhere? In other words, make sure that when Clang library parses the source code it has access to the body of this constructor - otherwise there's no way to generate the diagram for it...

**Comment by derived-coder** [comment]
> These lines should have an exact source file, line number and column - can you see the call to this constructor and the calls generated in the body of this constructor?

Yes is see the files and the lines are matching. So it means the header files are parsed?
No, it is completely header only library, everything is parsable by clang.

**Comment by bkryza** [comment]
@derived-coder Actually, I've just noticed that it's false by default, can you try setting:

`include_system_headers: true`

?

**Comment by derived-coder** [comment]
Okay now the pump is huge. I cannot open it anymore, but I see in the file that the classes are there
```
compilation_database_dir: build
output_directory: puml
diagrams:
  my_sequence_diagram:
    title: "My Sequence Diagram"
    type: sequence
    glob: [src/main.cpp]
    combine_free_functions_into_file_participants: true
    include_system_headers: true
    include:
      # Include only elements allowed by any of the filters below:
      anyof:
        namespaces:
          - my_ns
        elements:
          - r: "main.*"
    exclude:
      namespaces:
        - std
    from:
        - function:
            r: "main.*"
```

How can I now filter out the unwanted stuff?

**Comment by bkryza** [comment]
@derived-coder Ok, sorry, I forgot that whenever you want to analyze stuff included using angle brackets `#include <...>`, i.e. system headers, you have to set it to true.

Now to make the diagram smaller depends what you mean by unwanted stuff?

* You can for instance limit method calls only to public methods:

```yaml
   include:
     access:
       - public
```

You can exclude any `detail` namespaces:

```yaml
   exclude:
     namespaces:
       -r: ".*detail.*"
```

You can exclude calls based on callee types, e.g. to remove overloaded operator calls you can use:
```yaml
   exclude:
     callee_types:
       - operator
```

You can also exclude specific paths in that thirdparty library if they are not interesting:

```yaml
   exclude:
     paths:
       - /usr/lib/somelibrary/src/test
```

or you can include only elements from specific paths, e.g.:

```yaml
   exclude:
     paths:
       - src/main.cpp
       - /usr/lib/somelibrary/src/somecomponent
```

One more option you can set is `fold_repeated_activities: true`. Basically if some function or method is called multiple times, it is rendered in the diagram again with all its outgoing message. When you set this flag to true, it will only render such activity once, and any consecutive calls to this method will be replaced with a `*` symbol.

More filter examples for sequence diagrams can be found test cases [here](https://clang-uml.github.io/md_docs_2test__cases.html#sequence-diagrams) and in sequence diagrams documentation [here](https://clang-uml.github.io/md_docs_2sequence__diagrams.html).
