### ISSUE TITLE
Class diagram omits members from a class which is forward-declared elsewhere

### ISSUE THREAD

**Issue by lordvalumart** [bkryza/clang-uml#388]
Scenario:
- I have two classes `A` and `B`, each defined in their own cpp file
- `A.cpp` additionally contains a forward declaration for `B`

- I'm using clang-uml v0.6.0

If I configure clang-uml to process `A.cpp` then `B.cpp`, the generated class diagram omits `B`'s members. Processing the cpp files in the opposite order causes `B`'s members to appear in the diagram.

File contents are below:

```c++
// A.cpp
class B;

class A {
    B* pB_;
};
``` 
```c++
// B.cpp
class B {
    int b_;
};
``` 
```
# .clang-uml
diagrams:
  example_class_diagram:
    type: class
    glob:
      include:
        # Swap these lines to cause the generated diagram to contain B::b_
        - C:\example\A.cpp
        - C:\example\B.cpp
```
