### ISSUE TITLE
Add support for separators in class diagrams

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#55]
Currently methods and fields in classes are rendered in diagrams in no particular order. 

Preferably they should be ordered based on their access, sorted by name and also:
* Constructors first
* operator overloads
* other methods

Public, protected and private methods should be separated using dotted separators:
```
@startuml
class Foo1 {
  Foo()
  Foo(Foo&&)
  ..
  operator=()
  operator+=()
  ..
  do_sth()
}
@enduml
```

**Comment by bkryza** [comment]
Also it would be nice to have options to decide how the class elements should be ordered and grouped:
```
my_class_diagram:
  type: class
  ...
  methods_order: lexical # or 'declared' 
```
