### ISSUE TITLE
Add config file schema validation

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#57]
Currently configuration files are not validated for correcteness, for instance a typo such as:
```yaml
  exclude:
    namespace:
       - std 
```

instead of:
```yaml
  exclude:
    namespaces:
       - std 
```

will not produce any error but simply not apply the exclusion filter...
