### ISSUE TITLE
clang-uml fails to parse code for an arm target

### ISSUE THREAD

**Issue by bilboquet** [bkryza/clang-uml#59]
Hello,

I'm having a large embedded project build upon mbed (https://os.mbed.com/).
I wish I could use clang-uml to reverse some (if not all) parts of it to better understand it.

The project uses the dedicated mbed build system and gcc as its compiler. With the help of `bear` I've successfully made a `compile_commands.json` which seems fine (the `clangd` extension for `vscode` use it successfully, as well as `codechecker` (https://github.com/Ericsson/codechecker) that uses clang static-analyzer and Clang Tidy)).

When I try to run `clang-uml` over my project it exits very early with this error (many times)
```
.././mbed-os/targets/TARGET_STM/TARGET_STM32L4/STM32Cube_FW/STM32L4xx_HAL_Driver/stm32l4xx_ll_adc.h:6386:31: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
  const __IO uint32_t *preg = __ADC_PTR_REG_OFFSET(ADCx->JDR1, ((Rank & ADC_INJ_JDRX_REGOFFSET_MASK) >> ADC_JDRX_REGOFFSET_POS));
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.././mbed-os/targets/TARGET_STM/TARGET_STM32L4/STM32Cube_FW/STM32L4xx_HAL_Driver/stm32l4xx_ll_adc.h:378:34: note: expanded from macro '__ADC_PTR_REG_OFFSET'
  ((__IO uint32_t *)((uint32_t) ((uint32_t)(&(__REG__)) + ((__REG_OFFFSET__) << 2UL))))
                                 ^~~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
Erreur de segmentation (core dumped)

```
As the code is cross-compiled this should not be an issue.
As other clang based tools do not report this problem, I suppose that at some point `clang-uml` lost an information that make it fail.

Would you please help me? (either fix or disable the check would be ok)

**Comment by bkryza** [comment]
@bilboquet The problem here is that Stm32 is a 32-bit architecture so the cast is correct when compiling for Arm, but Clang parser used by `clang-uml` is not aware of that - can you share a subset of the `compile_commands.json` file - I'd like to see the compiler flags which are specified there...

`clang-tidy` probably works because it does check the Stm32 Cube headers

**Comment by bilboquet** [comment]
@bkryza thanks for your reply

The compile_commands.json is huge, so here is an extract [extract.zip](https://github.com/bkryza/clang-uml/files/9767489/extract.zip) (the original file has many entries like this, I've also removed some line that are special to my project but that should not interfere).
I agree with you that the problem is related to the stm32 being a 32bits while my pc is 64.
My guess is that `clang-tidy` interpret the flag `"-mcpu=cortex-m4"`.

If the extract is not ok for you, I may start over a new project that I could share.

Thank you

**Comment by bkryza** [comment]
@bilboquet I've managed to reproduce the error with the following steps:

```bash
python3 -m pip install mbed-tools
mbed-tools import mbed-os-example-blinky mbed-os-example-blinky
mbed-tools configure -m NUCLEO_F411RE -t GCC_ARM
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B cmake_build/NUCLEO_F411RE/develop/GCC_ARM  -GNinja
find . -name compile_commands.json
```
and the following `.clang-uml` config:

```yaml
compilation_database_dir: cmake_build/NUCLEO_F411RE/develop/GCC_ARM/
output_directory: puml
diagrams:
  test:
    type: class
    glob:
      - main.cpp
    include:
      namespaces:
        - test
    using_namespace:
      - test
```

I'll investigate if it's possible to resolve this issue...

**Comment by bkryza** [comment]
@bilboquet I've managed to generate a diagram from this code by adding a `-fms-extesions` compilation flag like this:
```bash
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="-fms-extensions" -S . -B cmake_build/NUCLEO_F411RE/develop/GCC_ARM  -GNinja
```
and commenting out these 2 lines in `mbed-os/platform/include/platform/mbed_retarget.h`:
```cpp
//typedef signed   int  ssize_t;  ///< Signed size type, usually encodes negative errors
typedef signed   long off_t;    ///< Offset in a data stream
typedef unsigned int  nfds_t;   ///< Number of file descriptors
//typedef unsigned long long fsblkcnt_t;  ///< Count of file system blocks
```

After that the diagram gets generated, although you still get a lot of warnings from Clang:
```bash
$ clang-uml
...
136 warnings generated.
[info] [tid 2839919] [main.cc:278] Written test diagram to puml/test.puml
$ cat puml/test.puml
@startuml
class "A" as C_0001009537205076478716
class C_0001009537205076478716 {
}
@enduml
```

I know it's not ideal, but for now I don't have a better solution...

**Comment by bilboquet** [comment]
Thanks a lot, not ideal but promising :)
I'll test this tomorrow and tell you what happens on my side

**Comment by bilboquet** [comment]
@bkryza 
Hello
I tested your suggestions and its quite better :)
Not perfect for sure but it gives some results.

# What I did
- commented the suggested `typedefs` in `mbed_retarget.h`
- as we are using the old `mbed` build tools (we are not using `cmake`) so I added `"-fms-extensions"` for every entry in the `compile_commands.json`
- fixed few warnings (that obviously must be fixed in our code)

adapt my `.clang-uml` file according to this:
```yaml
compilation_database_dir: .
output_directory: puml
diagrams:
  myproject_class:
    type: class
    glob:
      - main.cpp
    using_namespace:
      - traxens
    include:
      namespaces:
        - traxens
    exclude:
      namespaces:
        - mbed
        - std
    plantuml:
      after:
        - 'note left of {{ alias("MyProjectMain") }}: Main class of myproject library.'
```

- ran `clang-uml -v`

# The results

I ended up with this:

```shell
[debug] [tid 647827] [class_diagram_generator.cc:269] == Processing relationship --+
[debug] [tid 647827] [diagram.cc:258] Looking for alias for 967470598388489187
[debug] [tid 647827] [class_diagram_generator.cc:312] === Adding relation C_0000399580321923892100 --+ C_0000967470598388489187

clang-uml: /home/user/workspace/clang-uml/src/common/types.h:102: T& clanguml::common::optional_ref<T>::value() [with T = clanguml::common::model::diagram_element]: Assertion `value_ != nullptr' failed.
Abandon (core dumped)
```

Not ideal, but I have a 246kB `puml/myproject_class.puml` file that I can open with `plantuml`. As it's huge, for the moment I'm unable to tell if it's missing something in.

# Questions

- If you're interested in investigating this crash I'll be glad to help. Please just let me know.
- Is there any way to restrict the size of the generated model? As an example for a class diagram, limit it X levels of dependencies. (It could improve readability and maybe help to find the crash).

Once again, many thanks

**Comment by bkryza** [comment]
@bilboquet 
First of all, which version of `clang-uml` are you using? If you're building the latest master, can you please build it in debug mode:
```bash
make debug
```
and then run clang-uml in gdb:
```bash
gdb --args /path/to/clang-uml
(gdb) run
# Wait till it crashes
(gdb) bt full
```
and please paste the output (at least first 10 frames)

As to the size of the generated PlantUML file, the key idea behind `clang-uml` is to enable fine-grained generation of diagrams by specifying custom inclusion and exclusion directives, for instance if you're interested in direct neighborhood of a specific class just create a diagram like this:
```yaml
    include:
      namespaces:
        - traxens
      context:
        - traxens::MyClassA
```

Also you can try to remove dependency relationships which can clutter diagrams by adding `exclude` filter:
```yaml
    exclude:
      relationships:
        - dependency
```
More examples are in test cases [t00039](https://github.com/bkryza/clang-uml/blob/master/docs/test_cases/t00039.md) - [t00042](https://github.com/bkryza/clang-uml/blob/master/docs/test_cases/t00042.md)...
