### ISSUE TITLE
how to write config file if I don't have a name space in my cpp code

### ISSUE THREAD

**Issue by hunterzju** [bkryza/clang-uml#62]
for example, I don't declare a namespace in my code:
```c++
// main.cpp

class A {
};

class B : public A {
};

main() {
;
}
```

**Comment by bkryza** [comment]
@hunterzju here is a test case and example for such situation (adjust your paths accordingly):

https://github.com/bkryza/clang-uml/blob/master/docs/test_cases/t00045.md

basically skip `using_namespace` and `include..namespaces` directives and exclude as much as you need from your dependencies (definitely exclude `std`)

**Comment by hunterzju** [comment]
> @hunterzju here is a test case and example for such situation (adjust your paths accordingly):
> 
> https://github.com/bkryza/clang-uml/blob/master/docs/test_cases/t00045.md
> 
> basically skip `using_namespace` and `include..namespaces` directives and exclude as much as you need from your dependencies (definitely exclude `std`)

I get Err with such config:
```
compilation_database_dir: ../build/
output_directory: ../docs/01Iterator
diagrams:
  iterator_class:
    type: class
    glob:
      - ./*.cpp
      - ./*.hpp
      - ./*.h
    exclude:
      namespace:
        - std
```
there are some cpp files in the folder, I want to know if my conig has some error?
![image](https://user-images.githubusercontent.com/16730065/207611382-d5755496-6734-4fa3-a33e-305e01e2b461.png)

**Comment by bkryza** [comment]
@hunterzju Where in the project structure is your `.clang-uml` file? Can you paste here the output of:

```bash
find . -name "*.cpp"
find . -name "compile_commands.json"
find . -name ".clang-uml"
```

executed in your projects root directory, or at least some part of the output...

**Comment by hunterzju** [comment]
> @hunterzju Where in the project structure is your `.clang-uml` file? Can you paste here the output of:
> 
> ```shell
> find . -name "*.cpp"
> find . -name "compile_commands.json"
> find . -name ".clang-uml"
> ```
> 
> executed in your projects root directory, or at least some part of the output...

```
// tree ./ -la
├── Aggregate.h
├── Book.h
├── BookSelf.cpp
├── BookSelf.h
├── BookSelfIterator.cpp
├── BookSelfIterator.h
├── .clang-uml
├── CMakeLists.txt
├── .gdb_history
├── Iterator.h
├── main.cpp
└── ReadMe.md
```
and the "compile_commands.json" is in `../build/compile_commands.json`
my system is manjaro linux.

**Comment by hunterzju** [comment]
I run clang-uml with gdb and the error comes in 
![image](https://user-images.githubusercontent.com/16730065/207629538-15e60847-81dd-4e1d-9747-dd0c71695c21.png)

when I run next here, the error info printed:
![image](https://user-images.githubusercontent.com/16730065/207629964-7775d3b8-9029-41a5-8e8d-97919961852b.png)

**Comment by hunterzju** [comment]
It seems to get error in `src/util/util.cc: line 54`:
![image](https://user-images.githubusercontent.com/16730065/207632269-49622ab8-585d-45cd-91be-06bd6eb7610f.png)

**Comment by bkryza** [comment]
@hunterzju I've reproduced the problem, I'll try to fix it as your original config should work, but the following configuration should work for you:

```yaml
compilation_database_dir: ../build/
output_directory: ../docs/01Iterator
diagrams:
  iterator_class:
    type: class
    glob:
      - "*.cpp"
    exclude:
      namespaces:
        - std
```
