### ISSUE TITLE
Add row and column layout hints

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#90]
Sometimes it's useful to group elements in the diagram in rows or columns. This can be easily implemented by adding `row` and `column` layout hints. In PlantUML they can be rendered using `left` or `down` hidden links.

Config could look like:
```yaml

layout:
  A: 
    - row: [AA, AAA] # A, AA and AAA should be in the same row
  B:
    - row: [BBB, BBB]
  C:
    - column: [CCC, CCC] # C, CC and CCC should be in the same column
```
