### ISSUE TITLE
Add customizable Jinja `context` configuration option

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#95]
For configuration files with large number of diagrams which rely on Jinja templates, it would be useful to add `context` option to the inheritable config option set, which would enable for instance the following use case:

```yaml
...
context:
  author: bkryza
  copyright: Copyright (C) 2023
  my_condition_1: true
...
diagrams:
  my_class_diagram:
    type: class
    ...
    plantuml:
      after:
        - >
          note left of {{ alias("ClassA") }}
             {{ author }} {{ copyright }}
          end note
        - >
          {% if my_condition_1 %}
          note left of {{ alias("ClassB") }}
             {{ author }} {{ copyright }}
          end note
          {% endif %}
```

There should be also a command line option to override/add any context variable, e.g.:

```bash
clang-uml -n my_class_diagram --context "my_condition_1: false"
```
